//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthReg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ведущие> Ведущие { get; set; }
        public virtual DbSet<Занятия> Занятия { get; set; }
        public virtual DbSet<Курсы> Курсы { get; set; }
        public virtual DbSet<КурсыВедущих> КурсыВедущих { get; set; }
        public virtual DbSet<МестоПров> МестоПров { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
