//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Занятия
    {
        public int IDLesson { get; set; }
        public int Курс { get; set; }
        public string Тема { get; set; }
        public int Ведущий { get; set; }
        public System.DateTime Дата { get; set; }
        public int Стоимость { get; set; }
        public int Площадка { get; set; }
    
        public virtual Ведущие Ведущие { get; set; }
        public virtual Курсы Курсы { get; set; }
        public virtual МестоПров МестоПров { get; set; }
    }
}
