//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class КурсыВедущих
    {
        public int IDCs { get; set; }
        public Nullable<int> IDSpeak { get; set; }
        public Nullable<int> IDCourse { get; set; }
    
        public virtual Ведущие Ведущие { get; set; }
        public virtual Курсы Курсы { get; set; }
    }
}
